name: Update repository index

on:
  push:
    branches:
      - "main"

jobs:
  run:
    name: Generate index
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Generate index
        run: npx @teletron/extension-indexer

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Updated index.json, automatically."
          add: "index.json"
